name: test

on:
  - push
  - pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TZ: Asia/Tokyo

jobs:
  matrix:
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # If it fails in the middle, the remaining commands will not be executed
          - name: format
            command: >
              set -eo pipefail &&
              find . -name Cargo.toml -print0 |
              xargs -0 -n 1 cargo fmt --check --manifest-path
          - name: lint
            command: >
              set -eo pipefail &&
              find . -name Cargo.toml -exec
              sh -c 'cd "$(dirname {})" && cargo clippy -- -D warnings' \;
          - name: test
            command: >
              set -eo pipefail &&
              find . -name Cargo.toml -print0 |
              xargs -0 -n 1 cargo test --manifest-path
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy,rustfmt
      - uses: Swatinem/rust-cache@v2
      - run: ${{ matrix.command }}
